#!groovy
pipeline {

  agent any

  stages {
    stage ('Build') {
      steps {
        dir('user-service') {
          sh "../mvnw clean verify"
        }
      }
    }
    stage('Check Pact Verifications') {
      steps {
        sh 'curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.3/pact-1.88.3-linux-x86_64.tar.gz'
        sh 'tar xzf pact-1.88.3-linux-x86_64.tar.gz'
        dir('pact/bin') {
          sh "./pact-broker can-i-deploy -a user-service -b http://pact_broker -e ${GIT_COMMIT}"
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'junit5'
      }
      steps {
        echo 'Deploying to prod now...'
      }
    }
  }

}