#!groovy
pipeline {

  agent any

  parameters {
    string(name: 'pactConsumerTags', defaultValue: 'master', description: 'Tags to verify')
  }

  stages {
    stage ('Build') {
      steps {
        dir('user-service') {
          sh "../mvnw clean verify -Dpact.provider.version=${GIT_COMMIT} -Dpact.verifier.publishResults=true -Dpactbroker.tags=${params.pactConsumerTags}"
        }
      }
    }
  }

}